export const electronicsData =[
    {
      id: 1,
      name: 'OnePlus Mobile',
      category: 'Electronics',
      description: 'Smartphone with high-end features.',
      price: 18999.99,
      offerPrice: 17999.99,
      image: 'https://lifemobile.lk/wp-content/uploads/2023/07/one1.jpg',
      specifications: [
        '6.5-inch Super AMOLED display',
        'Quad-camera setup',
        'Snapdragon 865 processor',
        '5000mAh battery',
      ],
    },
    {
      id: 2,
      name: 'Sony Q-LED Smart TV',
      category: 'Electronics',
      description: 'Ultra HD Smart TV with HDR.',
      price: 85499.99,
      offerPrice: 64999.99,
      image: 'https://rukminim2.flixcart.com/image/850/1000/kae95e80/television/r/g/m/realme-tv-43-original-imafrz78gbgx3zz5.jpeg?q=20',
      specifications: [
        '55-inch 4K HDR display',
        'Smart TV functionality',
        'Dolby Atmos sound',
        'Multiple HDMI and USB ports',
      ],
    },
    
    {
      id: 5,
      name: 'Laptop',
      category: 'Electronics',
      description: 'High-performance laptop for professional use.',
      price: 108000.99,
      offerPrice: 99999.99,
      image: 'https://cdn.thewirecutter.com/wp-content/media/2023/06/businesslaptops-2048px-0943.jpg',
      specifications: [
        '15.6-inch Full HD display',
        'Intel Core i7 processor',
        '16GB RAM',
        '512GB SSD',
      ],
    },
    
    {
      id: 7,
      name: 'Gaming Console',
      category: 'Electronics',
      description: 'Next-gen gaming console for immersive gaming experiences.',
      price: 85000.99,
      offerPrice: 74999.99,
      image: 'https://assets.xboxservices.com/assets/c9/10/c910f756-7999-42c3-9f66-aa30fece2ae8.jpg?n=Consoles-Hub_Content-Placement_Hub-SS_788x444.jpg',
      specifications: [
        '4K gaming support',
        'Ray tracing technology',
        'High-speed SSD storage',
        'Wireless controller included',
      ],
    },
    {
      id: 8,
      name: 'Bluetooth Speaker',
      category: 'Electronics',
      description: 'Portable Bluetooth speaker for on-the-go music.',
      price: 1299.99,
      offerPrice: 999.99,
      image: 'https://avshack.in/cdn/shop/products/215a9d7e-3d8a-4f87-acd7-3d0c688d4aef.jpg?v=1645811304',
      specifications: [
        'Wireless Bluetooth connectivity',
        'Built-in rechargeable battery',
        'Water-resistant',
        'Compact and lightweight design',
      ],
    },
    {
      id: 10,
      name: 'Portable Bluetooth Speaker',
      category: 'Audio',
      description: 'Compact and portable Bluetooth speaker for on-the-go music.',
      price: 799.99,
      offerPrice: 599.99,
      image: 'https://m.media-amazon.com/images/I/71T1Iu2YCjL._AC_UF1000,1000_QL80_.jpg',
      specifications: [
        'Wireless Bluetooth connectivity',
        '10 hours of playback time',
        'Water-resistant design',
        'Built-in microphone for hands-free calls',
      ],
    },
    {
      id: 11,
      name: 'Home Security System',
      category: 'Smart Home',
      description: 'Smart home security system with cameras and sensors.',
      price: 2499.99,
      offerPrice: 1999.99,
      image: 'https://5.imimg.com/data5/SELLER/Default/2022/9/TJ/HR/QE/10089124/4hd-cctv-camera-setup-with-1-tb-hard-disk.jpg',
      specifications: [
        '1080p HD cameras',
        'Motion detection sensors',
        'Smartphone app integration',
        '24/7 monitoring',
      ],
    },
    {
      id: 12,
      name: 'Digital Camera',
      category: 'Cameras',
      description: 'Mirrorless digital camera with 4K video recording.',
      price: 152000.99,
      offerPrice: 112000.99,
      image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Canon_EOS_5D_Mark_IV_and_EF_11-24mm_F4L_USM.jpg/1200px-Canon_EOS_5D_Mark_IV_and_EF_11-24mm_F4L_USM.jpg',
      specifications: [
        '24.2MP APS-C sensor',
        '4K UHD video recording',
        '3-inch tilting touchscreen',
        'Built-in Wi-Fi',
      ],
    },
    {
      id: 13,
      name: 'Wireless Earbuds',
      category: 'Audio',
      description: 'True wireless earbuds with noise cancellation.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://www.jiomart.com/images/product/original/rvninkli2g/appslite-calfornia-us-made-air-earbuds-pro-white-with-active-noise-cancellation-anc-product-images-orvninkli2g-p599090130-0-202303061735.jpg?im=Resize=(420,420)',
      specifications: [
        'Active noise cancellation',
        'Touch controls',
        'Up to 20 hours of battery life',
        'IPX4 water resistance',
      ],
    },
    {
      id: 14,
      name: 'Gaming Laptop',
      category: 'Laptops',
      description: 'High-performance gaming laptop with RGB lighting.',
      price: 1499.99,
      offerPrice: 1399.99,
      image: 'https://beebom.com/wp-content/uploads/2023/08/Lenovo-LOQ-Gaming-Laptop.jpg?w=750&quality=75',
      specifications: [
        '15.6-inch FHD display',
        'Intel Core i7 processor',
        'NVIDIA GeForce RTX graphics',
        'RGB backlit keyboard',
      ],
    },
    {
      id: 15,
      name: 'Laptop',
      category: 'Electronics',
      description: 'Powerful laptop for work and entertainment.',
      price: 1299.99,
      offerPrice: 1199.99,
      image: 'https://firebasestorage.googleapis.com/v0/b/nandu-1121a.appspot.com/o/images%2Flaptop.jpg?alt=media&token=792a55ca-c4f7-4acb-917e-35df8d68a266',
      specifications: [
        '15.6-inch Full HD display',
        'Intel Core i7 processor',
        '16GB RAM, 512GB SSD',
        'Windows 10 OS',
      ],
    },
    {
      id: 17,
      name: 'Wireless Earphones',
      category: 'Electronics',
      description: 'Bluetooth earphones with noise cancellation.',
      price: 79.99,
      offerPrice: 79.99,
      image: 'https://m.media-amazon.com/images/I/61aocNxAWLL._AC_UF1000,1000_QL80_.jpg',
      specifications: [
        'Wireless Bluetooth connectivity',
        'Active noise cancellation',
        'Long battery life',
        'Sweat-resistant design',
      ],
    },
    {
      id: 18,
      name: 'Portable Speakers',
      category: 'Electronics',
      description: 'Compact speakers for on-the-go entertainment.',
      price: 49.99,
      offerPrice: 49.99,
      image: 'https://m.media-amazon.com/images/I/71T1Iu2YCjL._AC_UF1000,1000_QL80_.jpg',
      specifications: [
        'Bluetooth and AUX connectivity',
        'Portable and lightweight',
        'High-quality sound',
        'Built-in rechargeable battery',
      ],
    },
    {
      id: 19,
      name: 'iPhone 13',
      category: 'Electronics',
      description: 'Latest iPhone with advanced features.',
      price: 1099.99,
      offerPrice: 1099.99,
      image: 'https://media.wired.com/photos/6148ef98a680b1f2086efee0/1:1/w_1037,h_1037,c_limit/Gear-Review-Apple_iphone13_hero_us_09142021.jpg',
      specifications: [
        '6.1-inch Super Retina XDR display',
        'A15 Bionic chip with Neural Engine',
        'Dual-camera system with Night mode',
        'iOS 15 with App Library and Widgets',
      ],
    },
    {
      id: 21,
      name: 'Smart Watch',
      category: 'Wearables',
      description: 'Fitness tracker with heart rate monitoring.',
      price: 79.99,
      offerPrice: 79.99,
      image: 'https://m.media-amazon.com/images/I/71TIOhVWQ5L.jpg',
      specifications: ['Color display', 'Water-resistant', 'Bluetooth connectivity'],
    },
    {
      id: 22,
      name: 'Asus Wireless Mouse',
      category: 'Accessories',
      description: 'Ergonomic wireless mouse for improved productivity.',
      price: 29.99,
      offerPrice: 29.99,
      image: 'https://images-cdn.ubuy.co.in/6366bc2b8b91d3664d5b6ca5-ubuy-online-shopping.jpg',
      specifications: ['2.4GHz wireless technology', 'Long battery life', 'DPI adjustment'],
    },
    {
      id: 23,
      name: 'Boat Bluetooth Neck Band',
      category: 'Audio',
      description: 'Over-ear Bluetooth headphones for immersive sound.',
      price: 99.99,
      offerPrice: 79.99,
      image: 'https://images-static.nykaa.com/media/catalog/product/0/5/053f8e78904130854736_n1_.jpg?tr=w-500,pr-true',
      specifications: ['Noise isolation', 'Foldable design', 'Built-in microphone'],
    },
    {
      id: 24,
      name: 'Samsung External SSD',
      category: 'Storage',
      description: 'High-speed external SSD for data storage on the go.',
      price: 129.99,
      offerPrice: 129.99,
      image: 'https://img.global.news.samsung.com/in/wp-content/uploads/2016/03/T3_007_Dynamaic_Silver.jpg',
      specifications: ['2TB storage capacity', 'USB-C connectivity', 'Compact design'],
    },
    {
      id: 25,
      name: 'LG 4K Monitor',
      category: 'Monitors',
      description: 'Ultra HD monitor for crisp and clear visuals.',
      price: 399.99,
      offerPrice: 399.99,
      image: 'https://www.lg.com/in/images/monitors/md07566088/gallery/32UQ750-W-UltraWide-Monitor-leftside-view-D-04.jpg',
      specifications: ['31.5-inch display','4k', 'HDR support', 'Multiple connectivity options'],
    },
    {
      id: 26,
      name: 'Alienware  Keyboard',
      category: 'Gaming Accessories',
      description: 'Mechanical gaming keyboard with customizable RGB lighting.',
      price: 89.99,
      offerPrice: 79.99,
      image: 'https://www.dellstore.com/pub/media/catalog/product/cache/74ae05ef3745aec30d7f5a287debd7f5/k/e/keyboard-aw420k-xkb-05-bk-gallery-01_1_11zon_1.jpg',
      specifications: ['Mechanical switches', 'Customizable RGB', 'Programmable keys'],
    },
    {
      id: 27,
      name: 'Fitbit Fitness Tracker',
      category: 'Wearables',
      description: 'Track your steps, heart rate, and workouts with a fitness tracker.',
      price: 49.99,
      offerPrice: 49.99,
      image: 'https://media.littlewoods.com/i/littlewoods/QV9N9_SQ1_0000000269_WHITE_BLACK_SLf?$300x400_retinamobilex2$',
      specifications: ['Heart rate monitor', 'Sleep tracking', 'Waterproof design'],
    },
    {
      id: 28,
      name: 'Asus Portable Monitor',
      category: 'Monitors',
      description: 'Compact and portable monitor for dual-screen setups.',
      price: 179.99,
      offerPrice: 179.99,
      image: 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/81ufQKVY2fL.jpg',
      specifications: ['15.6-inch display', 'USB-C connectivity', 'Slim and lightweight'],
    },
    {
      id: 29,
      name: 'USB-C Hub',
      category: 'Accessories',
      description: 'Expand your laptop connectivity with a USB-C hub.',
      price: 49.99,
      offerPrice: 49.99,
      image: 'https://m.media-amazon.com/images/W/MEDIAX_792452-T2/images/I/71jq-Zqs6OL.jpg',
      specifications: ['Multiple ports (USB, HDMI, Ethernet)', 'Compact design', 'Plug and play'],
    },
    {
      id: 30,
      name: 'Solar Power Bank',
      category: 'Accessories',
      description: 'Charge your devices on the go with a solar power bank.',
      price: 39.99,
      offerPrice: 39.99,
      image: 'https://images-cdn.ubuy.co.in/634f569dbbe03807b7035f8c-waterproof-600000mah-power-bank-with.jpg',
      specifications: ['10000mAh capacity', 'Solar charging', 'Dual USB outputs'],
    },
    {
      id: 31,
      name: 'RedGear Gaming Mouse',
      category: 'Peripherals',
      description: 'High-precision gaming mouse with customizable RGB lighting.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://5.imimg.com/data5/SELLER/Default/2021/7/GT/CZ/HU/10044338/redgear-a-10-wired-gaming-mouse-with-led-lightweight-durable-and-dpi-upto-2400-500x500.jpg',
      specifications: [
        'DPI: 16000',
        'Programmable buttons: 8',
        'Polling rate: 1000Hz',
        'RGB lighting zones: 16.8 million colors',
      ],
    },
    {
      id: 32,
      name: 'Smart Thermostat',
      category: 'Smart Home',
      description: 'Wi-Fi-enabled thermostat for efficient temperature control.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://m.media-amazon.com/images/I/51JSqlt6xLL._AC_UF894,1000_QL80_.jpg',
      specifications: ['Remote control via smartphone app', 'Energy-saving features', 'Compatible with voice assistants'],
    },
    {
      id: 48,
      name: 'Mini Fridge',
      category: 'Appliances',
      description: 'Compact refrigerator for keeping beverages cool.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://5.imimg.com/data5/CO/PQ/MY-33574155/mini-fridge.jpg',
      specifications: ['20 liters capacity', 'Adjustable temperature control', 'Compact and portable'],
    },
    {
      id: 49,
      name: 'Honeywell Air Purifier',
      category: 'Appliances',
      description: 'Small air purifier for cleaner indoor air.',
      price: 59.99,
      offerPrice: 54.99,
      image: 'https://ii1.pepperfry.com/media/catalog/product/h/o/1100x1210/honeywell-air-touch-p2-air-purifier--h13-hepa--pm2-5-level-display--smart-wi-fi--honeywell-air-touch-lhvrr4.jpg',
      specifications: ['HEPA filter', 'Quiet operation', 'Compact design'],
    },
    {
      id: 50,
      name: 'Philips Light Bulb',
      category: 'Smart Home',
      description: 'Set of smart LED bulbs for customizable lighting.',
      price: 39.99,
      offerPrice: 34.99,
      image: 'https://cdn.vox-cdn.com/thumbor/twhweqrG_obtz7SoYGWKld_qgMM=/0x0:5250x3600/1400x1400/filters:focal(2625x1800:2626x1801)/cdn.vox-cdn.com/uploads/chorus_asset/file/22823524/philips_smart_led_bulb_package.jpg',
      specifications: ['Color-changing options', 'Compatibility with smart home systems', 'Energy-efficient'],
    },
    {
      id: 51,
      name: 'Tp-Link Wi-Fi Extender',
      category: 'Accessories',
      description: 'Extend your Wi-Fi coverage with a range extender.',
      price: 7799.99,
      offerPrice: 6799.99,
      image: 'https://cdn.tet.lv/tetveikals-prd-images/product_popup_image/products/tl-wa850re-us-05-60fe6f960fa71.jpg',
      specifications: ['Dual-band support', '300 mbps','Easy setup', 'Compact design'],
    },
    {
      id: 52,
      name: 'Smart Mirror',
      category: 'Smart Home',
      description: 'Mirror with built-in display for information and workouts.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://p.globalsources.com/IMAGES/PDT/S1175781115/Smart-Mirror.jpg',
      specifications: ['Full-length mirror with touchscreen', 'Fitness apps integration', 'Weather and news display'],
    },
    {
      id: 53,
      name: 'Bluetooth Car Kit',
      category: 'Car Accessories',
      description: 'Upgrade your car with Bluetooth connectivity.',
      price: 24.99,
      offerPrice: 19.99,
      image: 'https://veedee.in/cdn/shop/products/71ziRfrY6eL._SY450_grande.jpg?v=1669892791',
      specifications: ['Hands-free calling', 'Wireless music streaming', 'Easy installation'],
    },
    {
      id: 54,
      name: 'X1 Electric Scooter',
      category: 'Electronics',
      description: 'Portable electric scooter for urban commuting.',
      price: 299.99,
      offerPrice: 279.99,
      image: 'https://hoverpro.in/wp-content/uploads/2023/06/1-First-Image.jpg',
      specifications: ['Max speed: 15 mph', 'Foldable design', 'Long-lasting battery'],
    },
    {
      id: 55,
      name: 'Smart Coffee Table',
      category: 'Furniture',
      description: 'Coffee table with built-in wireless charging and storage.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://multitouchtables.net/wp-content/uploads/2019/08/smart-table-with-refrigerator-cooler-drawers.jpg',
      specifications: ['Wireless charging pad', 'Hidden storage compartments', 'Modern design'],
    },
    {
      id: 56,
      name: 'pTron Charging Stand',
      category: 'Accessories',
      description: 'Desktop stand with wireless charging for phones and earbuds.',
      price: 34.99,
      offerPrice: 29.99,
      image: 'https://ptron.in/cdn/shop/products/61w-RyPbPtS._SL1100.jpg?v=1632972007',
      specifications: ['Qi wireless charging', 'Adjustable stand', 'Compact and stylish'],
    },
    {
      id: 57,
      name: 'Havells Ceiling Fan',
      category: 'Smart Home',
      description: 'Ceiling fan with smart controls and built-in lights.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://technocart.com/cdn/shop/files/Havells-FHCBBULPLC48-00.png?v=1691477232',
      specifications: ['Smartphone app control', 'Dimmable LED lights', 'Voice control compatible'],
    },
    {
      id: 58,
      name: 'Godrej Digital Lock',
      category: 'Smart Home',
      description: 'Keyless entry with smartphone control and security features.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://www.3stechno.hexcart.com/shop/images/10091/Godrej-Electronic-Door-Lock-0-2cae54599aa52219a78c66e7de86b59b.webp',
      specifications: ['Remote locking and unlocking', 'Activity log', 'Secure access codes'],
    },
    {
      id: 59,
      name: 'Phillips Security Camera',
      category: 'Smart Home',
      description: 'Weather-resistant camera for outdoor surveillance.',
      price: 89.99,
      offerPrice: 79.99,
      image: 'https://cdn.staticans.com/image/tr:h-1500,w-1500,cm-pad_resize/catalog/brandstore/philips/254-2023_05_05-HSP_3800_1.jpg',
      specifications: ['1080p HD video', 'Motion detection', 'Night vision'],
    },
    {
      id: 60,
      name: 'Electric Standing Desk',
      category: 'Furniture',
      description: 'Height-adjustable desk for ergonomic workspace setup.',
      price: 299.99,
      offerPrice: 279.99,
      image: 'https://www.purpleark.in/cdn/shop/products/electric-height-adjustable-table-standard-415209.jpg?v=1699525715',
      specifications: ['Motorized height adjustment', 'Memory presets', 'Spacious work surface'],
    },
    {
      "id": 61,
      "name": " Desktop PC",
      "category": "Electronics",
      "description": "Powerful desktop computer for efficient multitasking  computing tasks.",
      "price": 999.99,
      "offerPrice": 899.99,
      "image": "https://www.illegear.com/shop/409/illegear-custom-gaming-desktop-pc.jpg",
      "specifications": [
        "Intel Core i7 Processor",
        "16GB RAM",
        "1TB SSD Storage",
        "NVIDIA GeForce RTX Graphics",
        "Wireless Keyboard and Mouse",
        "Multiple USB Ports",
        "High-Speed Ethernet",
        "Bluetooth Connectivity",
        "Windows 10 Pro",
        "Multi-monitor Support"
      ]
    },
    {
      id: 62,
      name: 'Wireless Microphone',
      category: 'Audio',
      description: 'Portable microphone for karaoke parties with wireless connectivity.',
      price: 39.99,
      offerPrice: 34.99,
      image: 'https://images-cdn.ubuy.co.in/635de0d5a367ef4677468394-mbuynow-wireless-bluetooth-karaoke.jpg',
      specifications: ['Bluetooth connectivity', 'Built-in speaker', 'Rechargeable battery'],
    },
    {
      id: 63,
      name: 'Syska Smart Plug',
      category: 'Smart Home',
      description: 'Control your devices remotely with this smart Wi-Fi plug.',
      price: 19.99,
      offerPrice: 14.99,
      image: 'https://5.imimg.com/data5/SELLER/Default/2021/12/DY/FD/NV/39776904/mini-wi-fi-enabled-mwp002-smart-plug-500x500.jpg',
      specifications: ['App-controlled power outlet', 'Voice control compatible', 'Energy monitoring'],
    },
    {
      "id": 64,
      "name": "Ultimate Tech Bundle",
      "category": "Electronics",
      "description": "Complete tech bundle featuring a high-performance laptop, versatile USB pendrive, and fast-charging accessories.",
      "price": 799.99,
      "offerPrice": 749.99,
      "image": "https://i5.walmartimages.com.mx/mg/gm/1p/images/product-images/img_large/00019702986224l.jpg",
      "specifications": [
        "Laptop: Intel Core i5 Processor",
        "Laptop: 8GB RAM",
        "Laptop: 512GB SSD Storage",
        "Laptop: 14-inch Full HD Display",
        "Pendrive: 128GB USB 3.0",
        "Charger: Quick Charge 3.0 Technology",
        "Charger: Multi-device Compatibility",
        "Charger: Foldable Plug Design",
        "Accessories: Laptop Bag Included",
        "Accessories: Wireless Mouse",
        "Accessories: USB-C to USB-A Adapter",
        "Accessories: Noise-Canceling Earphones"
      ]
    },    
    {
      "id": 65,
      "name": "Canon Eos7 Camera",
      "category": "Electronics",
      "description": "High-performance mirrorless camera with advanced features ",
      "price": 899.99,
      "offerPrice": 849.99,
      "image": "https://poojaelectronics.in/storage/2022/07/Canon-EOS-R7-Mirrorless-Camera-with-18-150mm-Lens-Online-Buy-India_01.jpg",
      "specifications": [
        "24MP Full-frame Sensor",
        "4K Video Recording at 60fps",
        "5-axis In-body Image Stabilization",
        "Wi-Fi and Bluetooth Connectivity",
        "Touchscreen LCD Display",
        "Interchangeable Lenses Compatibility",
        "Weather-sealed Body"
      ]
    },    
    {
      id: 66,
      name: 'Wireless Charging Mouse Pad',
      category: 'Accessories',
      description: 'Mouse pad with integrated wireless charging for compatible devices.',
      price: 29.99,
      offerPrice: 24.99,
      image: 'https://example.com/wireless_charging_mouse_pad.jpg',
      specifications: ['Qi wireless charging', 'Anti-slip surface', 'Compact design'],
    },
    {
      id: 67,
      name: 'Portable Espresso Maker',
      category: 'Appliances',
      description: 'Compact espresso maker for coffee lovers on the move.',
      price: 69.99,
      offerPrice: 64.99,
      image: 'https://example.com/portable_espresso_maker.jpg',
      specifications: ['Manual pump operation', 'Compact and lightweight', 'No batteries or electricity required'],
    },
    {
      id: 68,
      name: 'Smart LED Strip Lights',
      category: 'Smart Home',
      description: 'Color-changing LED strip lights with smart controls.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://example.com/smart_led_strip_lights.jpg',
      specifications: ['Customizable colors', 'App and voice control', 'Easy installation'],
    },
    {
      id: 69,
      name: 'In-Ear Sleep Headphones',
      category: 'Audio',
      description: 'Comfortable in-ear headphones designed for sleep and relaxation.',
      price: 39.99,
      offerPrice: 34.99,
      image: 'https://example.com/in_ear_sleep_headphones.jpg',
      specifications: ['Soft and flexible design', 'Noise-canceling', 'Comfortable for side sleepers'],
    },
    {
      id: 70,
      name: 'Smart Water Bottle',
      category: 'Fitness',
      description: 'Water bottle with hydration tracking and reminders.',
      price: 24.99,
      offerPrice: 19.99,
      image: 'https://example.com/smart_water_bottle.jpg',
      specifications: ['Bluetooth connectivity', 'Hydration goal reminders', 'BPA-free material'],
    },
    {
      id: 71,
      name: 'Wireless Charging Desk Lamp',
      category: 'Accessories',
      description: 'Desk lamp with wireless charging pad and adjustable brightness.',
      price: 44.99,
      offerPrice: 39.99,
      image: 'https://example.com/wireless_charging_desk_lamp.jpg',
      specifications: ['Wireless charging pad', 'Adjustable brightness levels', 'Modern design'],
    },
    {
      id: 72,
      name: 'Outdoor Bluetooth Speaker',
      category: 'Audio',
      description: 'Durable and waterproof Bluetooth speaker for outdoor use.',
      price: 59.99,
      offerPrice: 54.99,
      image: 'https://example.com/outdoor_bluetooth_speaker.jpg',
      specifications: ['Rugged design', '360-degree sound', 'Long battery life'],
    },
    {
      id: 73,
      name: 'Smart LED Bathroom Mirror',
      category: 'Smart Home',
      description: 'Bathroom mirror with built-in LED lights and smart features.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://example.com/smart_led_bathroom_mirror.jpg',
      specifications: ['Touchscreen controls', 'LED lighting with color options', 'Anti-fog function'],
    },
    {
      id: 74,
      name: 'Wireless Car Charger Mount',
      category: 'Car Accessories',
      description: 'Car mount with wireless charging for smartphones.',
      price: 34.99,
      offerPrice: 29.99,
      image: 'https://example.com/wireless_car_charger_mount.jpg',
      specifications: ['Qi wireless charging', 'Adjustable viewing angle', 'Secure grip'],
    },
    {
      id: 75,
      name: 'Smart Home Weather Station',
      category: 'Smart Home',
      description: 'Weather station with temperature, humidity, and weather forecast.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://example.com/smart_home_weather_station.jpg',
      specifications: ['Indoor and outdoor sensors', 'App integration', '7-day weather forecast'],
    },
    {
      id: 76,
      name: 'Bluetooth Karaoke Speaker',
      category: 'Audio',
      description: 'Portable Bluetooth speaker with built-in karaoke function.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://example.com/bluetooth_karaoke_speaker.jpg',
      specifications: ['Karaoke microphone included', 'RGB lights', 'Rechargeable battery'],
    },
    {
      id: 77,
      name: 'Compact Air Fryer',
      category: 'Appliances',
      description: 'Compact air fryer for healthier cooking with less oil.',
      price: 69.99,
      offerPrice: 64.99,
      image: 'https://example.com/compact_air_fryer.jpg',
      specifications: ['2.5-liter capacity', 'Adjustable temperature control', 'Timer function'],
    },
    {
      id: 78,
      name: 'Smart Refrigerator',
      category: 'Appliances',
      description: 'Refrigerator with advanced smart features for modern kitchens.',
      price: 1299.99,
      offerPrice: 1199.99,
      image: 'https://example.com/smart_refrigerator.jpg',
      specifications: [
        'French door design',
        '600 liters capacity',
        'Smart home integration (IoT)',
        'Touchscreen control panel',
        'Custom temperature zones',
      ],
    },
    {
      id: 79,
      name: '360-Degree Security Camera',
      category: 'Smart Home',
      description: 'High-resolution camera with panoramic view for comprehensive security.',
      price: 179.99,
      offerPrice: 169.99,
      image: 'https://example.com/360_security_camera.jpg',
      specifications: [
        '4K resolution',
        '360-degree field of view',
        'Motion tracking technology',
        'Night vision',
        'Two-way audio',
      ],
    },
    {
      id: 80,
      name: 'Ultra-Wide Curved Monitor',
      category: 'Monitors',
      description: 'Curved monitor for immersive gaming and productivity.',
      price: 499.99,
      offerPrice: 479.99,
      image: 'https://example.com/ultra_wide_curved_monitor.jpg',
      specifications: [
        '34-inch curved display',
        'UWQHD resolution',
        'Adaptive sync technology',
        '144Hz refresh rate',
        'HDR support',
      ],
    },
    {
      id: 81,
      name: 'Electric Skateboard',
      category: 'Outdoor',
      description: 'Motorized skateboard for electric-powered commuting and fun.',
      price: 299.99,
      offerPrice: 279.99,
      image: 'https://example.com/electric_skateboard.jpg',
      specifications: [
        'Max speed: 20 mph',
        'Wireless remote control',
        '15-mile range',
        'Regenerative braking',
        'Lightweight and portable',
      ],
    },
    {
      id: 82,
      name: 'Smart Thermostat',
      category: 'Smart Home',
      description: 'Programmable thermostat with energy-saving features and smart controls.',
      price: 89.99,
      offerPrice: 79.99,
      image: 'https://example.com/smart_thermostat.jpg',
      specifications: [
        '7-day programming',
        'Smartphone app control',
        'Energy usage reports',
        'Compatible with smart home platforms',
      ],
    },
    {
      id: 83,
      name: 'High-End Gaming PC',
      category: 'Electronics',
      description: 'Custom-built gaming PC for enthusiasts and esports players.',
      price: 1999.99,
      offerPrice: 1899.99,
      image: 'https://example.com/high_end_gaming_pc.jpg',
      specifications: [
        'Intel Core i9 processor',
        'NVIDIA GeForce RTX 3080 graphics',
        '32GB RAM',
        '1TB NVMe SSD + 2TB HDD',
        'Liquid cooling system',
      ],
    },
    {
      id: 84,
      name: 'Smart Lock with Facial Recognition',
      category: 'Smart Home',
      description: 'Biometric smart lock with facial recognition for enhanced security.',
      price: 249.99,
      offerPrice: 239.99,
      image: 'https://example.com/smart_lock_facial_recognition.jpg',
      specifications: [
        'Facial recognition technology',
        'Keyless entry',
        'Access logs and notifications',
        'Remote control via app',
      ],
    },
    {
      id: 85,
      name: '4K Ultra Short Throw Projector',
      category: 'Electronics',
      description: 'Projector with ultra-short throw for big-screen entertainment.',
      price: 1499.99,
      offerPrice: 1399.99,
      image: 'https://example.com/4k_short_throw_projector.jpg',
      specifications: [
        '4K UHD resolution',
        '150-inch screen size',
        'HDR support',
        'Built-in streaming apps',
        'Wireless connectivity',
      ],
    },
    {
      id: 86,
      name: 'Solar-Powered Outdoor Camera',
      category: 'Smart Home',
      description: 'Wireless outdoor camera with solar panel for continuous power.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/solar_powered_outdoor_camera.jpg',
      specifications: [
        'Wire-Free design',
        'Solar-powered battery',
        '1080p HD video',
        'Weather-resistant',
        'Smartphone alerts',
      ],
    },
    {
      id: 87,
      name: 'Gaming Desk with RGB Lighting',
      category: 'Furniture',
      description: 'Gaming desk with customizable RGB lighting for an immersive setup.',
      price: 199.99,
      offerPrice: 189.99,
      image: 'https://example.com/gaming_desk_rgb_lighting.jpg',
      specifications: [
        'Built-in RGB lighting strips',
        'Cable management system',
        'Carbon fiber textured surface',
        'Sturdy steel frame',
      ],
    },
    {
      id: 88,
      name: 'Robot Vacuum Cleaner with Mapping',
      category: 'Appliances',
      description: 'Smart vacuum cleaner with mapping technology for efficient cleaning.',
      price: 349.99,
      offerPrice: 329.99,
      image: 'https://example.com/robot_vacuum_cleaner_mapping.jpg',
      specifications: [
        'LIDAR mapping technology',
        'Scheduled cleaning',
        'Multiple cleaning modes',
        'Wi-Fi connectivity',
      ],
    },
    {
      id: 89,
      name: 'Wireless Charging Bedside Lamp',
      category: 'Accessories',
      description: 'Bedside lamp with integrated wireless charging pad for devices.',
      price: 59.99,
      offerPrice: 54.99,
      image: 'https://example.com/wireless_charging_bedside_lamp.jpg',
      specifications: [
        'Wireless charging pad',
        'Touch-sensitive controls',
        'Adjustable brightness levels',
        'USB port for additional charging',
      ],
    },
    {
      id: 90,
      name: 'Ultra-Lightweight Folding Electric Bike',
      category: 'Outdoor',
      description: 'Foldable electric bike for convenient urban commuting.',
      price: 699.99,
      offerPrice: 679.99,
      image: 'https://example.com/folding_electric_bike.jpg',
      specifications: [
        '250W electric motor',
        'Folding design for portability',
        '15.5-mile range',
        'LED headlight and taillight',
        'Adjustable seat height',
      ],
    },
    {
      id: 91,
      name: 'Smart Mirror with Fitness Trainer',
      category: 'Smart Home',
      description: 'Interactive smart mirror with built-in fitness trainer and apps.',
      price: 499.99,
      offerPrice: 479.99,
      image: 'https://example.com/smart_mirror_fitness_trainer.jpg',
      specifications: [
        'Full-length mirror with touchscreen',
        'Integrated camera for workouts',
        'AI-powered fitness trainer',
        'Smart home integration',
      ],
    },
    {
      id: 92,
      name: 'Professional Studio Microphone',
      category: 'Audio',
      description: 'High-quality studio microphone for professional audio recording.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://example.com/professional_studio_microphone.jpg',
      specifications: [
        'Cardioid pickup pattern',
        'Studio-grade audio quality',
        'Shock mount and pop filter included',
        'USB and XLR connectivity',
      ],
    },
    {
      id: 93,
      name: 'In-Ear Noise-Canceling Earphones',
      category: 'Audio',
      description: 'Compact in-ear earphones with advanced noise-canceling technology.',
      price: 89.99,
      offerPrice: 79.99,
      image: 'https://example.com/in_ear_noise_canceling_earphones.jpg',
      specifications: [
        'Active noise cancellation',
        'Hi-Res audio support',
        'Comfortable ergonomic design',
        'Wireless Bluetooth connectivity',
      ],
    },
    {
      id: 94,
      name: 'Electric Standing Desk',
      category: 'Furniture',
      description: 'Height-adjustable standing desk for ergonomic workspaces.',
      price: 299.99,
      offerPrice: 279.99,
      image: 'https://example.com/electric_standing_desk.jpg',
      specifications: [
        'Electric height adjustment',
        'Spacious work surface',
        'Programmable memory settings',
        'Sturdy steel frame',
      ],
    },
    {
      id: 95,
      name: 'Smart Garden Kit',
      category: 'Smart Home',
      description: 'Indoor smart garden kit for growing herbs and small plants.',
      price: 69.99,
      offerPrice: 64.99,
      image: 'https://example.com/smart_garden_kit.jpg',
      specifications: [
        'LED grow lights',
        'Self-watering system',
        'Smartphone app for monitoring',
        'Compact and stylish design',
      ],
    },
    {
      id: 96,
      name: 'Wireless Charging Mouse Pad',
      category: 'Accessories',
      description: 'Mouse pad with built-in wireless charging pad for compatible devices.',
      price: 34.99,
      offerPrice: 29.99,
      image: 'https://example.com/wireless_charging_mouse_pad.jpg',
      specifications: [
        'Qi wireless charging pad',
        'Large mouse surface',
        'Anti-slip rubber base',
        'LED charging indicator',
      ],
    },
    {
      id: 97,
      name: 'Smart Home Doorbell Camera',
      category: 'Smart Home',
      description: 'Video doorbell with smart features for home security and convenience.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/smart_doorbell_camera.jpg',
      specifications: [
        '1080p HD video',
        'Two-way audio communication',
        'Motion detection and alerts',
        'Night vision',
      ],
    },
    {
      id: 98,
      name: 'Digital Drawing Tablet',
      category: 'Electronics',
      description: 'Graphics tablet for digital art and professional illustration work.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/digital_drawing_tablet.jpg',
      specifications: [
        '10-inch drawing area',
        'Pressure-sensitive pen',
        'Programmable shortcut keys',
        'Compatible with popular drawing software',
      ],
    },
    {
      id: 99,
      name: 'Smart Car Charger',
      category: 'Accessories',
      description: 'Car charger with smart features for efficient and safe charging on the go.',
      price: 24.99,
      offerPrice: 19.99,
      image: 'https://example.com/smart_car_charger.jpg',
      specifications: [
        'Quick charge technology',
        'Built-in voltage and temperature monitoring',
        'Multiple USB ports',
        'LED indicator lights',
      ],
    },
    {
      id: 100,
      name: 'Outdoor Portable Projector Screen',
      category: 'Accessories',
      description: 'Portable projector screen for outdoor movie nights and events.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://example.com/outdoor_portable_projector_screen.jpg',
      specifications: [
        '100-inch diagonal screen size',
        'Foldable and lightweight design',
        'Front and rear projection options',
        'Easy setup and storage',
      ],
    },
    {
      id: 101,
      name: 'Ultra-HD Webcam with AI Features',
      category: 'Electronics',
      description: 'Webcam for high-quality video calls and AI-powered features.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://example.com/ultra_hd_webcam_ai_features.jpg',
      specifications: [
        '4K Ultra HD resolution',
        'Wide-angle lens',
        'Auto-focus and facial recognition',
        'Background blur technology',
        'AI-based noise cancellation',
        'Adjustable clip for multiple mounting options',
        'Compatibility with popular video conferencing apps',
      ],
    },
    {
      id: 102,
      name: 'Smart LED Light Bulbs',
      category: 'Smart Home',
      description: 'Smart bulbs with adjustable colors and smart home integration.',
      price: 29.99,
      offerPrice: 24.99,
      image: 'https://example.com/smart_led_light_bulbs.jpg',
      specifications: [
        '16 million color options',
        'Dimmable brightness',
        'Voice control (compatible with Alexa and Google Assistant)',
        'Scheduling and automation via app',
        'Energy-efficient LED technology',
        'Grouping for synchronized lighting scenes',
        'Long lifespan and low energy consumption',
      ],
    },
    {
      id: 103,
      name: 'Smart Desk Lamp with Wireless Charger',
      category: 'Accessories',
      description: 'Desk lamp with wireless charging pad and adjustable color temperature.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://example.com/smart_desk_lamp_wireless_charger.jpg',
      specifications: [
        'Wireless charging pad for Qi-compatible devices',
        'Adjustable color temperature and brightness',
        'Touch-sensitive controls',
        'USB port for additional charging',
        'Auto-off timer function',
        'Sleek and modern design',
        'Adjustable arm and head',
      ],
    },
    {
      id: 104,
      name: 'AI-Powered Home Assistant Robot',
      category: 'Smart Home',
      description: 'Robot assistant with artificial intelligence for household tasks.',
      price: 799.99,
      offerPrice: 779.99,
      image: 'https://example.com/ai_powered_home_assistant_robot.jpg',
      specifications: [
        'Voice recognition and natural language processing',
        'Facial recognition for personalized interactions',
        'Autonomous navigation and obstacle avoidance',
        'Integrated camera for remote monitoring',
        'Smart home device control',
        'Scheduled tasks and reminders',
        'Interactive touch screen',
      ],
    },
    {
      id: 105,
      name: 'Wireless Charging Mouse with RGB Lighting',
      category: 'Accessories',
      description: 'Gaming mouse with built-in wireless charging pad and customizable RGB lighting.',
      price: 69.99,
      offerPrice: 64.99,
      image: 'https://example.com/wireless_charging_mouse_rgb_lighting.jpg',
      specifications: [
        'Qi wireless charging technology',
        'Adjustable DPI up to 16000',
        'Programmable buttons and macros',
        'RGB lighting with customizable zones',
        'Ergonomic design for extended gaming sessions',
        'Onboard memory for saving settings',
        'Battery life indicator',
      ],
    },
    {
      id: 106,
      name: 'Smart WiFi Thermostat with Voice Control',
      category: 'Smart Home',
      description: 'WiFi-enabled thermostat with voice control and energy-saving features.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/smart_wifi_thermostat_voice_control.jpg',
      specifications: [
        'Remote control via smartphone app',
        'Voice control compatibility with virtual assistants',
        'Geofencing for automatic temperature adjustment',
        'Energy usage reports and recommendations',
        'Compatibility with smart home platforms',
        'Programmable scheduling for different times of the day',
        'Color touch screen display',
      ],
    },
    {
      id: 107,
      name: '4K Ultra Short Throw Laser Projector',
      category: 'Electronics',
      description: 'Short throw projector with laser technology for cinema-like visuals.',
      price: 1999.99,
      offerPrice: 1899.99,
      image: 'https://example.com/4k_ultra_short_throw_laser_projector.jpg',
      specifications: [
        '4K UHD resolution with HDR support',
        'Ultra-short throw design for minimal space requirements',
        'Laser light source for vivid and long-lasting colors',
        '150-inch diagonal projection size',
        'Built-in streaming apps',
        'Wireless connectivity options',
        'Integrated sound system',
      ],
    },
    {
      id: 108,
      name: 'Pro Gaming Mechanical Keyboard',
      category: 'Gaming Accessories',
      description: 'Mechanical gaming keyboard with customizable switches and RGB lighting.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/pro_gaming_mechanical_keyboard.jpg',
      specifications: [
        'Customizable mechanical switches (e.g., Cherry MX)',
        'RGB lighting with per-key customization',
        'Programmable macros and dedicated media controls',
        'N-Key rollover for anti-ghosting',
        'Detachable wrist rest for comfort',
        'Aluminum top plate for durability',
        'Compatible with gaming software for advanced customization',
      ],
    },
    {
      id: 109,
      name: 'Home Theater Sound System',
      category: 'Audio',
      description: 'Surround sound system with Dolby Atmos for immersive home theater experience.',
      price: 799.99,
      offerPrice: 769.99,
      image: 'https://example.com/home_theater_sound_system.jpg',
      specifications: [
        '5.1.4 channel configuration for three-dimensional audio',
        'Wireless subwoofer for deep bass',
        'Dolby Atmos and DTS:X support',
        'Bluetooth connectivity for streaming music',
        'HDMI eARC for high-quality audio transmission',
        'Smartphone app for easy setup and control',
        'Compatibility with voice assistants',
      ],
    },
    {
      id: 111,
      name: 'Smart Wi-Fi Light Bulbs (Set of 4)',
      category: 'Smart Home',
      description: 'Set of smart light bulbs with Wi-Fi connectivity for remote control.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://example.com/smart_wifi_light_bulbs.jpg',
      specifications: [
        'RGB color-changing capability',
        'Dimmable brightness control',
        'Voice control compatibility with virtual assistants',
        'Scheduling for automatic on/off',
        'Energy-efficient LED technology',
        'Grouping for synchronized lighting scenes',
        'Smartphone app for customization',
      ],
    },
    {
      id: 112,
      name: 'Cordless Electric Kettle',
      category: 'Appliances',
      description: 'Electric kettle for quick and convenient boiling of water.',
      price: 29.99,
      offerPrice: 24.99,
      image: 'https://example.com/cordless_electric_kettle.jpg',
      specifications: [
        '1.7-liter capacity',
        'Fast boiling with 1500W heating element',
        'Cordless design with 360-degree swivel base',
        'Auto shut-off and boil-dry protection',
        'Stainless steel construction',
        'Cool-touch handle for safe pouring',
        'Water level indicator',
      ],
    },
    {
      id: 113,
      name: 'Compact Robotic Vacuum Cleaner',
      category: 'Appliances',
      description: 'Autonomous robotic vacuum cleaner for efficient floor cleaning.',
      price: 199.99,
      offerPrice: 189.99,
      image: 'https://example.com/compact_robotic_vacuum_cleaner.jpg',
      specifications: [
        'Intelligent mapping and navigation',
        'Powerful suction with HEPA filter',
        'Scheduled cleaning routines',
        'Edge and corner cleaning mode',
        'Anti-drop and anti-collision sensors',
        'Remote control and smartphone app',
        'Low-profile design for accessing tight spaces',
      ],
    },
    {
      id: 114,
      name: 'Ultra-Slim 4K OLED TV',
      category: 'Electronics',
      description: 'Ultra-slim OLED TV with 4K resolution for stunning visuals.',
      price: 1499.99,
      offerPrice: 1449.99,
      image: 'https://example.com/ultra_slim_4k_oled_tv.jpg',
      specifications: [
        '55-inch OLED display with 4K UHD resolution',
        'Dolby Vision and HDR10+ support',
        '120Hz refresh rate for smooth motion',
        'Cinematic sound with Dolby Atmos',
        'Smart TV functionality with voice control',
        'Ultra-slim design with minimal bezels',
        'Multiple HDMI and USB ports',
      ],
    },
    {
      id: 115,
      name: 'Smart Refrigerator with Touchscreen',
      category: 'Appliances',
      description: 'Refrigerator with smart features and touchscreen for interactive control.',
      price: 1299.99,
      offerPrice: 1249.99,
      image: 'https://example.com/smart_refrigerator_with_touchscreen.jpg',
      specifications: [
        'French door design with touchscreen display',
        'Smart home integration for grocery management',
        'Adjustable temperature zones',
        'Water and ice dispenser with filtration',
        'Energy-efficient LED lighting',
        'Customizable storage shelves',
        'Camera for viewing contents remotely',
      ],
    },
    {
      id: 116,
      name: 'Portable Espresso Maker',
      category: 'Appliances',
      description: 'Compact espresso maker for coffee enthusiasts on the go.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://example.com/portable_espresso_maker.jpg',
      specifications: [
        '15-bar pressure for rich espresso shots',
        'Compatible with ground coffee or capsules',
        'Compact and lightweight design',
        'Rechargeable battery for cordless operation',
        'Boils water within minutes',
        'Includes a travel case',
        'Easy-to-clean components',
      ],
    },
    {
      id: 117,
      name: 'Smart Door Lock with Fingerprint Scanner',
      category: 'Smart Home',
      description: 'Smart door lock with biometric fingerprint scanner for enhanced security.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://example.com/smart_door_lock_fingerprint_scanner.jpg',
      specifications: [
        'Keyless entry with biometric fingerprint recognition',
        'Numeric keypad for PIN code access',
        'Remote control and monitoring via smartphone app',
        'Tamper and break-in alerts',
        'Battery-powered with long battery life',
        'Durable and weather-resistant construction',
        'Easy DIY installation',
      ],
    },
    {
      id: 118,
      name: 'Ultra-Wide Curved Gaming Monitor',
      category: 'Monitors',
      description: 'Curved gaming monitor with ultra-wide display for immersive gaming.',
      price: 699.99,
      offerPrice: 679.99,
      image: 'https://example.com/ultra_wide_curved_gaming_monitor.jpg',
      specifications: [
        '34-inch curved display with QHD resolution',
        '165Hz refresh rate and 1ms response time',
        'AMD FreeSync and NVIDIA G-Sync compatibility',
        'HDR400 for vibrant colors and high contrast',
        'Adjustable stand for ergonomic positioning',
        'Multiple gaming modes and presets',
        'RGB lighting on the back panel',
      ],
    },
    {
      id: 119,
      name: 'AI-Powered Language Translator Device',
      category: 'Electronics',
      description: 'Handheld language translator with AI for real-time translation.',
      price: 89.99,
      offerPrice: 84.99,
      image: 'https://example.com/ai_powered_language_translator.jpg',
      specifications: [
        'Supports multiple languages for two-way translation',
        'Built-in AI for context-aware translations',
        'Offline mode for translation without internet',
        'Large touchscreen for easy operation',
        'Compact and portable design',
        'Voice recognition and pronunciation guide',
        'Long-lasting battery life',
      ],
    },
    {
      id: 120,
      name: 'Multi-Zone Home Audio System',
      category: 'Audio',
      description: 'Whole-home audio system with multi-zone control and streaming capabilities.',
      price: 899.99,
      offerPrice: 879.99,
      image: 'https://example.com/multi_zone_home_audio_system.jpg',
      specifications: [
        'Multi-room audio with individual zone control',
        'High-fidelity speakers with room calibration',
        'Wireless streaming via Wi-Fi and Bluetooth',
        'Touchscreen control panel and smartphone app',
        'Supports popular music streaming services',
        'Expandable system for additional zones',
        'Voice control with virtual assistants',
      ],
    },
    {
      id: 121,
      name: 'Smart Pet Feeder',
      category: 'Smart Home',
      description: 'Automated pet feeder with app control and camera for remote monitoring.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/smart_pet_feeder.jpg',
      specifications: [
        'Scheduled feeding times via smartphone app',
        'Built-in camera for live video streaming',
        'Portion control for pets health management',
        'Two-way audio for communication with pets',
        'Removable and dishwasher-safe feeding tray',
        'Alerts for low food levels and feeding status',
        'Compatible with various pet food sizes and shapes',
      ],
    },
    {
      id: 122,
      name: 'Foldable Electric Scooter',
      category: 'Electronics',
      description: 'Portable electric scooter with foldable design for convenient commuting.',
      price: 349.99,
      offerPrice: 329.99,
      image: 'https://example.com/foldable_electric_scooter.jpg',
      specifications: [
        '250W brushless motor for smooth acceleration',
        'Max speed of 15.5 mph and 15.5 miles range',
        'Foldable design for easy carrying and storage',
        'Dual braking system for enhanced safety',
        'LED headlight and taillight for nighttime visibility',
        'Digital display for speed and battery status',
        'Shock-absorbing tires for a comfortable ride',
      ],
    },
    {
      id: 123,
      name: 'Robot Lawn Mower',
      category: 'Smart Home',
      description: 'Autonomous lawn mower with AI navigation for effortless lawn maintenance.',
      price: 499.99,
      offerPrice: 479.99,
      image: 'https://example.com/robot_lawn_mower.jpg',
      specifications: [
        'AI navigation for efficient and random cutting patterns',
        'Adjustable cutting height and width',
        'Weather-resistant and durable construction',
        'Quiet operation for day or night use',
        'Sensors for obstacle detection and avoidance',
        'App control for scheduling and monitoring',
        'Efficient battery for extended mowing sessions',
      ],
    },
    {
      id: 124,
      name: 'Wireless Charging Desk Pad',
      category: 'Accessories',
      description: 'Desk pad with integrated wireless charging for a clutter-free workspace.',
      price: 59.99,
      offerPrice: 54.99,
      image: 'https://example.com/wireless_charging_desk_pad.jpg',
      specifications: [
        'Large desk pad with wireless charging area',
        'Qi wireless charging compatibility for smartphones',
        'Non-slip surface for stable device placement',
        'Additional USB ports for wired charging',
        'LED indicator for charging status',
        'Water-resistant and easy to clean surface',
        'Sleek and minimalist design',
      ],
    },
    {
      id: 125,
      name: 'Digital Drawing Tablet',
      category: 'Electronics',
      description: 'Graphics tablet with a stylus for digital art and design work.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/digital_drawing_tablet.jpg',
      specifications: [
        '10-inch drawing area with high sensitivity',
        'Battery-free stylus with pressure sensitivity',
        'Customizable shortcut buttons for efficiency',
        'Compatible with popular graphic design software',
        'Adjustable stand for ergonomic drawing angles',
        'Connects to devices via USB or wireless',
        'Compatible with Windows and Mac operating systems',
      ],
    },
    {
      id: 126,
      name: 'Smart Water Bottle',
      category: 'Accessories',
      description: 'Water bottle with a smart hydration reminder and temperature monitoring.',
      price: 29.99,
      offerPrice: 24.99,
      image: 'https://example.com/smart_water_bottle.jpg',
      specifications: [
        'Hydration tracking with LED indicator',
        'Temperature sensor for monitoring drink temperature',
        'BPA-free and durable materials',
        'Bluetooth connectivity with smartphone app',
        'Long-lasting battery life with easy recharging',
        'Leak-proof design for on-the-go use',
        'Sleek and ergonomic shape',
      ],
    },
    {
      id: 127,
      name: 'Solar-Powered Outdoor Security Camera',
      category: 'Smart Home',
      description: 'Wireless outdoor security camera with solar panel for eco-friendly power.',
      price: 179.99,
      offerPrice: 169.99,
      image: 'https://example.com/solar_powered_security_camera.jpg',
      specifications: [
        '1080p HD video recording with night vision',
        'Wireless connectivity for easy installation',
        'Solar panel for continuous charging',
        'Weather-resistant and durable construction',
        'Motion detection with customizable zones',
        'Two-way audio for remote communication',
        'Cloud and local storage options',
      ],
    },
    {
      id: 128,
      name: 'Smart Mirror with Fitness Tracker',
      category: 'Smart Home',
      description: 'Interactive mirror with integrated fitness tracking and workout guidance.',
      price: 499.99,
      offerPrice: 479.99,
      image: 'https://example.com/smart_mirror_fitness_tracker.jpg',
      specifications: [
        'Full-length mirror with embedded LCD display',
        'Fitness tracking for real-time performance metrics',
        'Guided workouts with visual and audio instructions',
        'Personalized workout plans and progress tracking',
        'Bluetooth connectivity with heart rate monitors',
        'Sleek and stylish design for any room',
        'Voice control with virtual assistants',
      ],
    },
    {
      id: 129,
      name: 'Digital Photo Frame with Touchscreen',
      category: 'Electronics',
      description: 'Digital photo frame with a touchscreen for easy photo management and display.',
      price: 89.99,
      offerPrice: 79.99,
      image: 'https://example.com/digital_photo_frame_touchscreen.jpg',
      specifications: [
        '10-inch high-resolution touchscreen display',
        'Internal storage for storing and displaying photos',
        'Slideshow and customizable photo transitions',
        'Cloud connectivity for remote photo uploads',
        'Auto-adjusting brightness based on ambient light',
        'Multiple photo format compatibility',
        'Built-in speakers for background music',
      ],
    },
    {
      id: 130,
      name: 'Smart Thermostat with Voice Control',
      category: 'Smart Home',
      description: 'Programmable thermostat with voice control for energy-efficient temperature management.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/smart_thermostat_voice_control.jpg',
      specifications: [
        'Voice control with virtual assistants',
        'Programmable temperature schedules',
        'Remote control via smartphone app',
        'Energy usage tracking and reports',
        'Compatible with popular HVAC systems',
        'Built-in sensors for occupancy and temperature',
        'Sleek and modern design for any home',
      ],
    },
    {
      id: 131,
      name: 'Compact Air Purifier',
      category: 'Appliances',
      description: 'Portable air purifier with HEPA filter for clean and fresh indoor air.',
      price: 69.99,
      offerPrice: 59.99,
      image: 'https://example.com/compact_air_purifier.jpg',
      specifications: [
        'HEPA filter for effective airborne particle removal',
        'Compact and lightweight design for easy placement',
        'Quiet operation for use in bedrooms and offices',
        'Multiple fan speed settings for customization',
        'Filter replacement indicator for maintenance',
        'Energy-efficient with low power consumption',
        'Suitable for rooms up to 200 square feet',
      ],
    },
    {
      id: 132,
      name: 'Smart Home Weather Station',
      category: 'Smart Home',
      description: 'Weather station with multiple sensors for comprehensive weather monitoring.',
      price: 149.99,
      offerPrice: 139.99,
      image: 'https://example.com/smart_home_weather_station.jpg',
      specifications: [
        'Indoor and outdoor temperature and humidity sensors',
        'Barometric pressure and weather trend display',
        'Wind speed and direction sensor',
        'Rain gauge for accurate precipitation measurement',
        'Wireless connectivity with smartphone app',
        'Customizable alerts for specific weather conditions',
        'LCD display with easy-to-read weather data',
      ],
    },
    {
      id: 133,
      name: 'Portable Smart Projector',
      category: 'Electronics',
      description: 'Compact smart projector with built-in streaming and app functionality.',
      price: 199.99,
      offerPrice: 189.99,
      image: 'https://example.com/portable_smart_projector.jpg',
      specifications: [
        '720p HD resolution for clear and vibrant images',
        'Built-in streaming apps and screen mirroring',
        'Compact and lightweight design for portability',
        'Adjustable focus and keystone correction',
        'Built-in speakers for audio playback',
        'Wireless connectivity with smartphones and tablets',
        'Long-lasting battery for extended use',
      ],
    },
    {
      id: 134,
      name: 'Smart Window Blinds',
      category: 'Smart Home',
      description: 'Motorized window blinds with smart home integration for automated control.',
      price: 129.99,
      offerPrice: 119.99,
      image: 'https://example.com/smart_window_blinds.jpg',
      specifications: [
        'Motorized blinds with remote control',
        'Smart home integration with voice control',
        'Scheduled opening and closing for energy efficiency',
        'Adjustable slat angles for light control',
        'Battery-powered with long battery life',
        'Customizable to fit various window sizes',
        'Easy installation without the need for wiring',
      ],
    },
    {
      id: 135,
      name: '360-Degree Security Camera',
      category: 'Smart Home',
      description: 'Security camera with a 360-degree panoramic view for comprehensive surveillance.',
      price: 159.99,
      offerPrice: 149.99,
      image: 'https://example.com/360_degree_security_camera.jpg',
      specifications: [
        '360-degree panoramic view with fisheye lens',
        'High-resolution video recording with night vision',
        'Motion tracking and object detection',
        'Two-way audio for remote communication',
        'Smartphone app for real-time monitoring',
        'Cloud and local storage options',
        'Easy installation on ceilings or walls',
      ],
    },
    {
      id: 136,
      name: 'Smart Plant Monitor',
      category: 'Smart Home',
      description: 'Wireless plant monitor for tracking soil moisture, sunlight, and temperature.',
      price: 49.99,
      offerPrice: 44.99,
      image: 'https://example.com/smart_plant_monitor.jpg',
      specifications: [
        'Soil moisture, sunlight, and temperature sensors',
        'Wireless connectivity with smartphone app',
        'Customizable plant database for accurate monitoring',
        'Alerts for watering and sunlight requirements',
        'Long-lasting battery for continuous use',
        'Compact and unobtrusive design',
        'Suitable for indoor and outdoor plants',
      ],
    },
    {
      id: 137,
      name: 'Smart Electric Toothbrush',
      category: 'Accessories',
      description: 'Electric toothbrush with smart features for personalized oral care.',
      price: 79.99,
      offerPrice: 74.99,
      image: 'https://example.com/smart_electric_toothbrush.jpg',
      specifications: [
        'Sonic vibration technology for effective cleaning',
        'Smart sensors for tracking brushing habits',
        'Pressure sensor to prevent excessive brushing force',
        'Multiple cleaning modes for customization',
        'Bluetooth connectivity with a companion app',
        'Long battery life with USB charging',
        'Compact and travel-friendly design',
      ],
    },
    {
      id: 138,
      name: 'Smart Kitchen Scale',
      category: 'Appliances',
      description: 'Digital kitchen scale with smart features for precise cooking measurements.',
      price: 34.99,
      offerPrice: 29.99,
      image: 'https://example.com/smart_kitchen_scale.jpg',
      specifications: [
        'High-precision weighing with tare function',
        'Bluetooth connectivity with a recipe app',
        'Nutritional information for common ingredients',
        'Touchscreen display for easy operation',
        'Compact and slim design for easy storage',
        'Units conversion for versatile usage',
        'Durable and easy-to-clean stainless steel surface',
      ],
    },
];
export const appliancesData=[
    {
        id: 16,
        name: 'Samsung Refrigerator',
        category: 'Appliances',
        description: 'Large capacity refrigerator with multiple compartments.',
        price: 999.99,
        offerPrice: 899.99,
        image: 'https://firebasestorage.googleapis.com/v0/b/nandu-1121a.appspot.com/o/images%2Frefrigirator.jpg?alt=media&token=e5d77abe-cd14-4b05-b360-7ebd3b5cebcc',
        specifications: [
          'Double door design',
          '400 liters capacity',
          'Frost-free cooling',
          'LED lighting',
        ],
      },
      {
        id: 9,
        name: 'Coffee Maker',
        category: 'Appliances',
        description: 'Automatic drip coffee maker for your daily caffeine fix.',
        price: 79.99,
        offerPrice: 79.99,
        image: 'https://images.philips.com/is/image/philipsconsumer/72dbb6e1509a4cacb631ad1900d54b9e?wid=420&hei=360&$jpglarge$',
        specifications: [
          '12-cup capacity',
          'Programmable timer',
          'Pause and pour feature',
          'Removable filter basket',
        ],
      },
      {
        id: 3,
        name: 'Air Conditioner',
        category: 'Appliances',
        description: 'Split AC with energy-saving technology.',
        price: 899.99,
        offerPrice: 899.99,
        image: 'https://motorolain.vtexassets.com/arquivos/MotoAC-1000x700px-2.jpg',
        specifications: [
          '1.5-ton capacity',
          'Energy-efficient cooling',
          'Split-type design',
          'Remote control included',
        ],
      },
      // Additional items
      {
        id: 4,
        name: 'Washing Machine',
        category: 'Appliances',
        description: 'Front-load washing machine with multiple wash programs.',
        price: 599.99,
        offerPrice: 599.99,
        image: 'https://firebasestorage.googleapis.com/v0/b/nandu-1121a.appspot.com/o/images%2Fwashing%20machine.jpg?alt=media&token=13628cb1-38fb-47b8-90fd-60bb4980c277',
        specifications: [
          '8kg capacity',
          'Quick wash feature',
          'Energy-efficient',
          'Digital display',
        ],
      },
      {
        id: 6,
        name: 'Refrigerator',
        category: 'Appliances',
        description: 'French door refrigerator with ice maker.',
        price: 1099.99,
        offerPrice: 1099.99,
        image: 'https://whirlpoolindia.vtexassets.com/arquivos/ids/165870/340L-3S-INV-CNV-EXTUI-STEEL_Grey.jpg?v=638143820463230000',
        specifications: [
          '26 cubic feet capacity',
          'Water and ice dispenser',
          'Adjustable shelves',
          'Energy Star certified',
        ],
      },
]